### ISSUE TITLE
The Updated .py File Doesn't Work

### ISSUE THREAD

**Issue by PasswordOnOsu** [120-cell/osu-standard-to-mania-converter#1]
[This error](https://imgur.com/a/1QJhMaZ) ends up popping up whenever I try to use it. I used the previous file to see if it was something wrong with the new file, and the previous file ended up working perfectly fine. 

Also I noticed some differences between the 2 files (not necessarily issues, just observations):
1 - In the [new file](https://imgur.com/a/zeamZI9), the configurable section at the top is now in all caps. I have no idea if this effects anything in particular.
2 - You spelled "length" incorrectly in the new file.
3 - "hold_length_beats" current value is default to 0 instead of 1/4. Having the previous default value might be better to have as a default since it would let the person know that it's configuration is done with a "/4" in "1/4" or "/8" in "3/8" (as examples) which isn't stated anywhere. (I could see people getting confused and making mistakes with configuring it.)
4 - "STARTING_LANE" was previously "starting_column". I have no idea if that effects anything, I'm assuming this was done on purpose.
5 - There's now "import sys" which wasn't in the [previous file](https://imgur.com/a/1Dbw4Y6). I have no idea what this effects or if it played a role in the new file not working for me.
6 - I'm assuming the issue has something to do with the "sys.argv" section **possibly** since "../test" pops up at the end of the error.

**Comment by 120-cell** [comment]
The error appeared because I forgot to remove a line that set command line arguments manually for debugging (that's sys.argv). I should be fixed now.

1 -  All caps are the convention for constants that are defined once and never changed during code execution, but if it's annoying to read I can change it back.
2 - Spelling is fixed.
3 - 0.25 would give the same result as 1/4, in the latter case the program just does one more step of dividing 1 by 4.
4 - yes it was on purpose, since I think they're usually called lanes in mania.
